### PR TITLE
fix broken links, add sigmoid_tanh, fix clt formulation

### PR DESCRIPTION
**Pull request by zouharvi**
The sum of independent identically distributed random variables does not converge to normal distribution. The sum needs to be properly normalized (centralized and divided by the square root of n times the variance). [Source](https://en.wikipedia.org/wiki/Central_limit_theorem)

Fix broken links for TIMIT and Penn Treebank. Lowercase letters did not work correctly.

Add tanh from sigmoid image for greater clarity. I wasn't able to find a proper alignment option using the slimd framework and hence resorted to use plain html.

### CODE REVIEW

**Comment by zouharvi** [comment]
I just realized that merging several (although minor) issues together is not generally a good practice plus it decreases the number of extra points I get (1 per pull request).
Should I open a new pull request for each of the mentioned issues?

**Comment by darthdeus** [comment]
@zouharvi Just a thought, I'm not 100% sure but leaving this here anyway:

> The sum of independent identically distributed random variables does not converge to normal distribution. The sum needs to be properly normalized (centralized and divided by the square root of n times the variance).

Consider `X1 + X2 + ... + Xn = Y` for arbitrary iid Xi. If `(Y - mu) / sigma ~ N(0, 1)`, then by the affine transformation property of a Gaussian we get `Y ~ N(mu, sigma^2)`, which even though is not the standardized Gaussian is still a Gaussian. Or am I missing something?

**Comment by zouharvi** [comment]
@darthdeus, I am not sure about `(Y - mu) / sigma ~ N(0, 1)`. Shouldn't it be `(Y - mu) / (sigma * sqrt(n)) ~ N(0, 1)`? 
The square root of n is the problem.

**Comment by darthdeus** [comment]
The affine property is true for arbitrary sigma. I’m not saying anything
about what the true variance of the sum is, I’m just trying to explain that
it is (I’m about 99% sure :) ) a Gaussian regardless how it is normalized.

CLT requires the variance to be finite, and if a Gaussian is non-degenerate
with finite variance, you can always normalize it using the affine property
to obtain a normalized one.

**Comment by zouharvi** [comment]
@darthdeus You may actually be right and if that's the case I apologize for unnecessary correction. :-) 
I'll think about it.

**Comment by foxik** [comment]
I think that if we have *Xᵢ* which are IID, then *∑ Xᵢ* converges to *𝓝(nμ, nσ²)* and therefore *∑ Xᵢ/n* converges to *𝓝(μ, σ²/n)*, so I would not bother stating it including the normalization. Thanks for the corrected links (they worked some time ago) and for a nice picture. The images can be also positioned with SliMD, I will change it after merging (I will merge tomorrow).

**Comment by foxik** [comment]
Merging and will update in following commits.

**Pull request merged**
