### PR TITLE
Add batching for evaluation & move training, ... to functions.

### PR DESCRIPTION
**Pull request by petrroll**
- Moves training, evaluating, and prediction&save to separate functions
  - Makes creating more complex behaviors (early stopping, ...) easier.
- Adds an option to batch dev evaluation (off by default)
  - On higher resolution (32x32x32) the dev set doesn't fit in memory even on Colab's 12GB GPU with moderately sized networks. 
  - Controlled by a parameter and off by default because it distorts evaluation summaries.

### CODE REVIEW

**Comment by martinerk0** [comment]
Colab's GPU does not have 12GB, it is shared between multiple people.

**Comment by foxik** [comment]
Sorry for the delay; I am not a big fan of defining the helper methods in this case. For the `nsketch_transfer` template, I added batched evaluation (and batch prediction) directly to the Network methods, with correctly reporting evaluation scores -- would you be fine of using similar structure here as well? You can either backport it yourself, or I will get to it (but probably in the second half of the week).

**Comment by petrroll** [comment]
Yep, I saw that. While I believe my helper methods approach (despite not
being as elegant) provides a bit more flexibility your's is perfectly fine
as well.

I'll try to backport your changes tomorrow.

Btw: is there any benefit in backporting it even further to already
finished tasks? Essentially, do you plan on reusing the templates next year?

(Not promising I'll backport it to all previous tasks, just curious).

**Comment by foxik** [comment]
While I definitely agree your approach is a bit more flexible, I like the level of details of my version (and the fact that there is only one level of indirection). But it is definitely highly subjective.

Yes, I plan to reuse the templates next year, but hopefully Tensorflow Eager (i.e., TF 2.0) will be mature by then. That means large parts of the templates are going to change anyway, notably graph construction, training/evaluation cycles etc. So I think it does not make much sense to backport the improvements into past tasks.

(BTW, I will talk about Eager on one hand and XLA and TPU on the other, on one of the last lectures.)

**Comment by petrroll** [comment]
Should be ready to merge (didn't have time to test it, tho).

**Comment by foxik** [comment]
Thanks, there are some pieces of the original version left, I will take care of it.

**Comment by petrroll** [comment]
Sorry, I'll be more thorough next time :).

**Pull request merged**
